### ISSUE TITLE
整理UnfinishedTasks和UnassignedTasks

### ISSUE THREAD

**Issue by sharonWU0505** [sharonWU0505/Greedy-Algorithm#58]
1. `UnassignedTasks`目前輸出的順序是sorting過的順序，改回去以`taskid`排序會比較好看
2. `UnfinishedTasks`需要想一下怎麼寫比較好。因為re_calculate時我們會把無法再排入的task拿掉，所以該task有被做過，但不會出現在最終的`new_unassignedtasks`中，如果只檢查`new_unassignedtasks`會無法判斷到該task也是unfinished

**Comment by msjh80311** [comment]
那就直接放進`UnfinishedTasks`囉
我之前的想法是`UnassignedTasks` 就是只放那些完全沒做的task，也沒有特別想說要記錄做一半的，畢竟每個task最後完成的比例都可以從`TaskPercentages`裡取得

**Comment by sharonWU0505** [comment]
好阿~~

**Comment by msjh80311** [comment]
你在 `SecondStage` 裡面寫了"create UnfinishedTasks" 是想要做什麼事情啊？
